### ISSUE TITLE
Paragem errada: "R República (P Combustível)"

### ISSUE THREAD

**Issue by ScriptForAll** [carrismetropolitana/pdfs#2]
**Descreva o erro**  
_Uma explicação clara e concisa sobre o erro identificado._
No Bairro Espinhal, no concelho de Loures, a paragem que tem o nome "R República (P Combustível)" tem o nome errado. Isto deve-se ao facto de não existir nem uma Rua da República nem um posto de combustível no local. 
A paragem é efectuada pelas linhas 2025, 2705 e 2727 e friso que o próprio nome da paragem aparece mencionado nas alíneas.

**Área(s) afetada(s)**  
Quais as áreas afetadas pelo erro identificado:

- [ ] Área 1 (Viação Alvorada)
- [x] Área 2 (Rodoviária de Lisboa)
- [ ] Área 3 (TST)
- [ ] Área 4 (Alsa Todi)

**Ficheiro(s) afetado(s)**  
_Se possível, coloque o link direto para cada ficheiro:_

2025: [Loures > Sacavém](https://horarios.carrismetropolitana.pt/wp-content/uploads/horarios/2025/Linha_2025_070032_G_2022-12-12-18-52..pdf) ; [Sacavém > Loures
](https://horarios.carrismetropolitana.pt/wp-content/uploads/horarios/2025/Linha_2025_070533_R_2022-12-12-18-52..pdf)

[2705](https://horarios.carrismetropolitana.pt/wp-content/uploads/horarios/2705/Linha_2705_060207_C_2022-12-19-11-43..pdf)

2727: [Loures > Oriente](https://horarios.carrismetropolitana.pt/wp-content/uploads/horarios/2727/Linha_2727_070032_R_2022-12-27-15-51.pdf) ; [Est Oriente > Loures](https://horarios.carrismetropolitana.pt/wp-content/uploads/horarios/2727/Linha_2727_060207_G_2022-12-27-15-51.pdf)

**Valor(es) esperado(s)**  
_Se possível, uma descrição clara e concisa da situação sem erro / situação corrigida._
Passar a ter o nome "B Espinhal (Terminal)" pois corrige o problema e evidencia o facto de ser uma paragem terminal.

**Screenshots**  
_Se fizer sentido, adicione imagens que ajudem a explicar o problema._
N/A

**Contexto adicional**  
_Adicione qualquer outra informação útil à resolução do problema._

Este erro é particularmente urgente de se resolver uma vez que se trata de uma paragem terminal de algumas variantes e/ou linhas das que estão supramencionadas. Desse modo, pode induzir as pessoas em erro de forma a fazê-las pensar que o autocarro termina em Loures e não no Bº Espinhal.

**Comment by joao-vasconcelos** [comment]
= #3

**Comment by patriciataborda** [comment]
A designação correta para a paragem é "R Com Ramiro Correia (B Espinhal)" - código 070076

**Comment by joao-vasconcelos** [comment]
Designação alterada para as paragens `070075` e `070076`. Seguirá para o GTFS e PDFs em breve. Obrigado
